Chat space view完成
ux-latte/chat-space pull request #2
Opened 2019-03-04 08:46 UTC by ux-latte

#WHAT
ビュー部分の完成

#WHY
カリキュラム

2019-03-04 08:51 UTC, ghost requested changes
CSSは作ってないのでしょうか？

また、実装した画面のキャプチャをこちらに貼ってください。

2019-03-04 08:51 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +  %body
ここより上はapplication.html.hamlに記載されていると思うのですが、ここに書いている理由はなんですか？

2019-03-04 08:51 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +        %a
link_to ~ doで仮置きしておきましょう

2019-03-04 09:16 UTC, ux-latte commented on app/views/messages/index.html.haml
> +  %body
application.html.hamlを確認せずに記述してしまいました。

実装した画面のキャプチャです。
<img width="943" alt="2019-03-04 17 56 59" src="https://user-images.githubusercontent.com/47977234/53722711-813a7d80-3ea9-11e9-8613-e47625b4ef47.png">

2019-03-04 09:17 UTC, ux-latte commented
<img width="943" alt="2019-03-04 17 56 59" src="https://user-images.githubusercontent.com/47977234/53722826-b8109380-3ea9-11e9-8d5d-80e10393b3dc.png">

2019-03-06 03:21 UTC, ux-latte commented on app/views/messages/index.html.haml
> +        %a
link_to doに修正しました。

2019-03-06 03:31 UTC, TOMARUMARU approved these changes
LGTM

2019-03-06 03:33 UTC, merged